# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0002_auto_20190425_0747'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
            ],
        ),
    ]
