# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0004_auto_20190425_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='budget',
        ),
    ]
