# Generated by Django 2.2 on 2019-04-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0005_remove_organization_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='user',
            new_name='owner',
        ),
    ]
