# Generated by Django 2.2 on 2019-04-26 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0006_auto_20190426_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='investor',
            field=models.ManyToManyField(related_name='investorsList', through='investment_app.Investment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
